{"name": "test_add[1-2-5]", "status": "failed", "statusDetails": {"message": "AssertionError: assert (1 + 2) == 5", "trace": "a = 1, b = 2, c = 5\n\n    @pytest.mark.parametrize(*get_data_from_sheet(\"../data/test_data.xlsx\", \"add_test\"))\n    def test_add(a, b, c):\n>       assert a + b == c\nE       assert (1 + 2) == 5\n\nget_excel.py:46: AssertionError"}, "parameters": [{"name": "a", "value": "1"}, {"name": "b", "value": "2"}, {"name": "c", "value": "5"}], "start": 1617095612758, "stop": 1617095612758, "uuid": "5213a17b-8148-4024-aea0-9cb05ea4a27e", "historyId": "2eb157d7b868e33781e20b4ef2ebdcb7", "testCaseId": "74ccce3e7083777f7191b642997bae93", "fullName": "common.get_excel#test_add", "labels": [{"name": "parentSuite", "value": "common"}, {"name": "suite", "value": "get_excel"}, {"name": "host", "value": "DESKTOP-MI5M7JM"}, {"name": "thread", "value": "8880-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "common.get_excel"}]}