{"name": "test_i", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n2 Failed Assumptions:\n\ntest_class.py:59: AssumptionFailure\n>>\tpytest.assume(5 == 3)\nAssertionError: assert False\n\ntest_class.py:60: AssumptionFailure\n>>\tpytest.assume(4 == 5)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               2 Failed Assumptions:\nE               \nE               test_class.py:59: AssumptionFailure\nE               >>\tpytest.assume(5 == 3)\nE               AssertionError: assert False\nE               \nE               test_class.py:60: AssumptionFailure\nE               >>\tpytest.assume(4 == 5)\nE               AssertionError: assert False\n\n..\\venv\\lib\\site-packages\\six.py:702: FailedAssumption"}, "start": 1617003831722, "stop": 1617003831721, "uuid": "1ea68c26-9171-457d-a1d7-704b6e0aa7a5", "historyId": "36dc13f29d609c0bf711a84f25dbd362", "testCaseId": "57975a1ebc28fbbccef7273ac42c166c", "fullName": "cases.test_class.TestClass#test_i", "labels": [{"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_class"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "DESKTOP-MI5M7JM"}, {"name": "thread", "value": "16760-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_class"}]}